# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 잇다 - 정성을 담다.
email: 5zzang+itda@gmail.com
description: 잇다를 찾아주셔서 감사합니다. 

keywords: 잇다, 밀키트, 오리고기, 오리주물럭, 반만요리해, 캠핑메이트, 한끼뚝딱, 간편조리식

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://itda.5zzang.com" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  5zzang
facebook_username:  5zzang
twitter_username:  5zzang
google_analytics_tracking_id: UA-129738661-1
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
incremental: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
#exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ['.htaccess']
